services:
  athenaeum:
    container_name: athenaeum
    image: ghcr.io/bothari/athenaeum:latest
    ports:
      - "8741:8741"
    volumes:
      - ./data:/data
      - /path/to/media/books:/output
      - /path/to/downloads:/downloads
    environment:
      - DATA_DIR=/data
